#!/bin/bash
set -euo pipefail

# Fetch latest release version from GitHub
echo "[INFO] Fetch latest release version from GitHub..."
latest_release=$(curl -s https://api.github.com/repos/kabiiQ/BeatmapExporter/releases/latest)
pkgver=$(echo "$latest_release" | grep -oP '"tag_name": "\K(.*)(?=")')
echo "[INFO] latest ver: $pkgver"

# Loop through all subdirectories (recursively)
find . -type f -name "PKGBUILD" | while read -r pkgbuild; do
    dir=$(dirname "$pkgbuild")
    echo "Processing: $dir"

    if [[ -z "$pkgver" ]]; then
        echo "[EROR] Failed to get latest version for $dir"
        continue
    fi

    # Replace pkgver line in PKGBUILD
    sed -i -E "s/^pkgver=.*/pkgver=${pkgver}/" "$pkgbuild"

    # Print updated line for confirmation
    grep "^pkgver=" "$pkgbuild"
done
